server:
  port: 8050
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:123456@peer1:8761/eureka,http://eureka:123456@peer2:8762/eureka
    healthcheck:
      enable: true
  instance:
    prefer-ip-address: true
spring:
  application:
    name: microservice-file-upload
  http:
    multipart:
      max-file-size: 1Mb
      max-request-size: 5Mb